title = "Alarm server configuration"

[broker]
ip = "127.0.0.1"
port = 5672
username = "guest"
password = "guest"

[db]
url = "http://127.0.0.1:9000"
table = "Alarms"

[alarm]
path = "examples/config.yaml"
