title = "Alarm server configuration"

[broker]
ip = "127.0.0.1"
port = 5672
username = "guest"
password = "guest"

[db]
url = "https://obscure-space-rotary-phone-5vqvv7xpv4r3pp5p-9000.app.github.dev"
table = "Alarms"

[alarm]
path = "examples/config.yaml"
